# Generated by Django 5.2.10 on 2026-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetaSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('preferred_genre', models.CharField(choices=[('idle', 'Idle Games'), ('rpg', 'RPG'), ('vn', 'Visual Novel'), ('puzzle', 'Puzzle')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
